### ISSUE TITLE
Create source code for generating demo data

### ISSUE THREAD

**Issue by jhornert** [genevaers/demo#1]
Demonstration data will be small, but this code will be used to generate much more data to be able to run a demonstration of what GenevaERS can do. When done, copy the source code for this into the Demo Repo. Need to decide what folder we should create to put the source in for the Repo.

**Comment by neilbeesley** [comment]
Source code to generate test data TESTGEN5. NBEESLE.ASM on Kanplex.
Code needs to be pushed to repository.

**Comment by KipTwitchell** [comment]
Done and published.  Published in the Utilities Repo
