### ISSUE TITLE
Documentation for the Demo System

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/demo#14]
This should include perhaps:
Links to LR, LF and PF documentation.
The connection to the mainframe jcl execution step
Description of the view
Best Practices link for naming conventions

**Comment by emorrow38** [comment]
I have created a simple website  - [https://genevaers.github.io/demo/](url)
 Another way you can find this site is:
1.  Go to GitHub **Genevaers Demo** repo
2.  Click on **Settings**
3.  Scroll down to GitHub Pages and click on the link there.

The documentation (markdown files) are held in the "**docs**" folder.

The website is part of the Demo repo, which keeps everything together.

I have provided topic "**What is GenevaERS?**" - less than 140 words.

Those who know about the demo can supply info as follows:

|  To add details about:       |	Update file                      |
| ---------------------------- | ---------------------------- |
| Install the demo   | docs\InstallDemo.md |
| What demo does (views etc.) |  docs\WhatDemoDoes.md |
| Data Generator  | docs\DataGenerator.md  |

If we need more topics, let me know.  Feel free to update the markdown files shown in the table.
For a reference on markdown, see [https://www.markdownguide.org/cheat-sheet/](https://www.markdownguide.org/cheat-sheet/.)

I have not finished working on this website.  I am still working on the following:

1.  Will put in links to other documentation (when that other documentation is ready).
2.  Add a GenevaERS logo.
3.  Add a Jekyll theme to make the appearance a bit more mellow.  Proving a fiddly thing to do.
4.  Will help with markdown and topics as requested.

**Comment by KipTwitchell** [comment]
Issue complete.
