### ISSUE TITLE
Create base demo data for installation

### ISSUE THREAD

**Issue by jhornert** [genevaers/demo#2]
The demonstration data is a small subset of data to be part of the installation package to download. This will be the base demo data that will be extrapolated by tools run in the demonstration configuration process to create a larger quantity of data for the Demo execution.

**Comment by neilbeesley** [comment]
TESTGEN5 creates:

NBEESLE.CUSTADDR
NBEESLE.CUSTNAME
NBEESLE.CUSTOMER
NBEESLE.ORDERITM
NBEESLE.ORDER001
NBEESLE.PRODDESC
NBEESLE.PRODUCT

**Comment by KipTwitchell** [comment]
Decided to create JCL to run the Data Generator rather than downloading the data.
