### ISSUE TITLE
Create the multi-step join view

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/demo#5]
Describe / Create the view files and reference files for multi-step join and what data will be in the extra file.

**Comment by jhornert** [comment]
Create Store Address data to be used in a 2 step lookup from Order Item to Order to Store Address.

**Comment by neilbeesley** [comment]
View 10715 created in SAFRWBTR environment 4.

**Comment by jhornert** [comment]
View id 10715 is in Database=DM12; Schema=SAFRWBTR; SAFR Environment= Training Master(4).
The view is Format Phase Fixed Width using a 2 step lookup writing out to DDName=DAGSTATO. 
Description of view: The output contains a record of the summary of the quantity of Product sold per Product Id and State Where Sold the product was sold.

**Comment by KipTwitchell** [comment]
View built.  Issue resolved.
