### ISSUE TITLE
Create view with extract and summarization / aggregation

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/demo#6]
Describe / create the view - the files and what is the aggregation.

**Comment by neilbeesley** [comment]
Views:
10702 and 10714 which read output (token) from 10700.
in SAFRWBTR environment 4 (DM12).

**Comment by jhornert** [comment]
View ids 10700, 10702 and 10714 are in Database=DM12; Schema=SAFRWBTR; SAFR Environment= Training Master(4).
The view 10700 is an Extract Phase view that looks up to the Order file and writes to a SAFR Token. The SAFR token is read by two Token reading Format Phase views 10702 and 10714. View 10714 also does an effective date lookup.  

Description of view 10700: Reads the Item Event file and looking up to the Order file to obtain information including the Order Date to be used by views reading the SAFR Token this is writing to. 

Description of view 10702: Reads SAFR Token from view 10700. This does a lookup to the Customer file to obtain the original date the customer's account was create. The output file contains a record of the summary of Current Year Sales, Previous 5 Years Sales, Prior 6 to 10 Year Sales and Total Sales per unique Customer Id. This writes to the DDName = DCUSTORO.

Description of view 10714: Reads SAFR Token from view 10700. This does an effective date lookup to the Customer Name file to obtain the Customers Name when the order occurred. It does an effective date lookup to the Customer Address file to obtain the Customer Address when the order occurred. The output file contains a record of the summary of Current Year Sales, Previous 5 Years Sales, Prior 6 to 10 Year Sales and Total Sales per unique Customer Id, Customer Name and Customer Address. This writes to the DDName = DCOBYSTO.

**Comment by KipTwitchell** [comment]
View built, issue complete.
